FROM nginx
COPY src/static /var/www/static
COPY nginx.conf /etc/nginx/nginx.conf.template
CMD ["/bin/sh" , "-c" , "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
